name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: write greet to txt file 
        run: echo 'Hellow world!' > greetings.txt
      - name: check that the txt file exist 
        run: ls -la 
      - name: greet
        run: cat greetings.txt
      - name: greet with name
        run: echo "Hello, ${{ github.actor }}" > greetings.txt
      - name: cat after second greet
        run: cat greetings.txt
      
